document.addEventListener('DOMContentLoaded', () => {
    const startBtn = document.getElementById('start-btn');
    const compUrlInput = document.getElementById('competition-url');
    const agentStatus = document.getElementById('agent-status');
    const downloadReportBtn = document.getElementById('download-report-btn');
    
    // API Configuration from config.js
    const API_BASE = CONFIG.API_BASE;
    
    // Chat Elements
    const chatWidget = document.getElementById('chat-widget');
    const chatHeader = document.getElementById('chat-header');
    const chatInput = document.getElementById('chat-input');
    const sendChatBtn = document.getElementById('send-chat-btn');
    const chatMessages = document.getElementById('chat-messages');

    let fullAnalysisContext = "";
    
    // Graph Nodes mapped to the 6-Agent Architecture
    const nodes = [
        { id: 'node-explanation', name: 'Overview', elem: document.getElementById('node-explanation') },
        { id: 'node-data', name: 'Data', elem: document.getElementById('node-data') },
        { id: 'node-approaches', name: 'Approaches', elem: document.getElementById('node-approaches') },
        { id: 'node-winners', name: 'Winners', elem: document.getElementById('node-winners') },
        { id: 'node-discussion', name: 'Forum', elem: document.getElementById('node-discussion') },
        { id: 'node-code_hunter', name: 'Code Scout', elem: document.getElementById('node-code_hunter') }
    ];
    
    const nodeMapping = {
        'explanation': 0,
        'data': 1,
        'approaches': 2,
        'winners': 3,
        'discussion': 4,
        'code_hunter': 5
    };
    
    const edges = document.querySelectorAll('.edge');

    // Chat Toggle
    chatHeader.addEventListener('click', () => {
        chatWidget.classList.toggle('collapsed');
    });

    function resetGraph() {
        nodes.forEach(node => {
            node.elem.classList.remove('active', 'completed');
        });
        edges.forEach(edge => {
            edge.classList.remove('active', 'completed');
        });
        agentStatus.textContent = 'Waiting for task initialization...';
        downloadReportBtn.style.display = 'none';
        fullAnalysisContext = "";
        
        // Hide all cards
        document.querySelectorAll('.info-card').forEach(card => {
            card.classList.remove('visible');
            card.querySelector('.card-content').innerHTML = '<i class="fa-solid fa-circle-notch fa-spin" style="color:var(--primary-color)"></i> Loading data...';
        });

        // Reset chat
        chatInput.disabled = true;
        sendChatBtn.disabled = true;
    }

    function updateGraphNode(index, status) {
        if (index < 0 || index >= nodes.length) return;
        
        const node = nodes[index];
        
        if (status === 'active') {
            node.elem.classList.add('active');
            agentStatus.textContent = `Current Step: Analyzing ${node.name}...`;
            
            if (index > 0) {
                edges[index - 1].classList.add('active');
            }
        } else if (status === 'completed') {
            node.elem.classList.remove('active');
            node.elem.classList.add('completed');
            
            if (index > 0) {
                edges[index - 1].classList.remove('active');
                edges[index - 1].classList.add('completed');
            }
        }
    }

    // Use marked.js for proper markdown formatting
    function formatTextToHTML(text) {
        if(!text) return "";
        try {
            return marked.parse(text);
        } catch (e) {
            console.error("Markdown parsing error", e);
            return text;
        }
    }

    // Download Report Function
    downloadReportBtn.addEventListener('click', () => {
        const sections = [
            { title: "Competition Overview", id: "content-explanation" },
            { title: "Data Audit", id: "content-data" },
            { title: "Elite Approaches", id: "content-approaches" },
            { title: "Winning Solutions", id: "content-winners" },
            { title: "Community Intelligence", id: "content-discussion" },
            { title: "Code Scout Links", id: "content-external_links" }
        ];

        let markdownContent = `# Kaggle Analysis Report: ${compUrlInput.value}\nGenerated by KaggleAgent.AI (devparikh)\n\n---\n\n`;
        
        sections.forEach(s => {
            const elem = document.getElementById(s.id);
            if (elem && elem.innerText !== "Loading...") {
                markdownContent += `## ${s.title}\n\n${elem.innerText}\n\n---\n\n`;
            }
        });

        const blob = new Blob([markdownContent], { type: 'text/markdown' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `Kaggle_Analysis_${new Date().getTime()}.md`;
        a.click();
    });

    // Chat Logic
    async function sendMessage() {
        const text = chatInput.value.trim();
        if (!text) return;

        chatInput.value = '';
        appendMessage('user', text);

        try {
            const response = await fetch(`${API_BASE}/api/chat`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    message: text,
                    context: fullAnalysisContext
                })
            });

            const data = await response.json();
            appendMessage('bot', data.response);
        } catch (e) {
            appendMessage('bot', "Sorry, I lost connection to the Grandmaster server.");
        }
    }

    function appendMessage(sender, text) {
        const msgDiv = document.createElement('div');
        msgDiv.className = `message ${sender}-message`;
        msgDiv.innerHTML = formatTextToHTML(text);
        chatMessages.appendChild(msgDiv);
        chatMessages.scrollTop = chatMessages.scrollHeight;
    }

    sendChatBtn.addEventListener('click', sendMessage);
    chatInput.addEventListener('keypress', (e) => {
        if (e.key === 'Enter') sendMessage();
    });

    startBtn.addEventListener('click', async () => {
        const url = compUrlInput.value.trim();

        if (!url) {
            alert('Please provide a Kaggle competition URL.');
            return;
        }

        startBtn.disabled = true;
        startBtn.classList.add('running');
        startBtn.innerHTML = '<span>Analyzing...</span> <i class="fa-solid fa-circle-notch fa-spin"></i>';
        
        resetGraph();
        agentStatus.textContent = `Initializing Analysis for ${url}`;

        try {
            const response = await fetch(`${API_BASE}/api/run`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ url: url })
            });

            const reader = response.body.getReader();
            const decoder = new TextDecoder();
            let currentNodeIndex = -1;

            while (true) {
                const { value, done } = await reader.read();
                if (done) break;
                
                const chunk = decoder.decode(value);
                const lines = chunk.split('\n').filter(line => line.trim() !== '');
                
                for (const line of lines) {
                    try {
                        const data = JSON.parse(line);
                        
                        if (data.type === 'state_update') {
                            if (currentNodeIndex >= 0) updateGraphNode(currentNodeIndex, 'completed');
                            currentNodeIndex = nodeMapping[data.node];
                            if (currentNodeIndex !== undefined) updateGraphNode(currentNodeIndex, 'active');
                        } 
                        else if (data.type === 'content_update') {
                            const cardId = `card-${data.section}`;
                            const contentId = `content-${data.section}`;
                            const cardElem = document.getElementById(cardId);
                            const contentElem = document.getElementById(contentId);
                            
                            if (cardElem && contentElem) {
                                cardElem.classList.add('visible');
                                contentElem.innerHTML = formatTextToHTML(data.content);
                                fullAnalysisContext += `\n\nSECTION: ${data.section}\n${data.content}`;
                            }
                        }
                        else if (data.type === 'result') {
                            if (currentNodeIndex >= 0) updateGraphNode(currentNodeIndex, 'completed');
                            agentStatus.textContent = 'Analysis Complete! All insights displayed below.';
                            downloadReportBtn.style.display = 'flex';
                            chatInput.disabled = false;
                            sendChatBtn.disabled = false;
                        }
                        else if (data.type === 'error') {
                            agentStatus.textContent = 'Error: ' + data.message;
                        }
                    } catch (e) {}
                }
            }
        } catch (error) {
            agentStatus.textContent = 'Connection failed. Is the backend running?';
        } finally {
            startBtn.disabled = false;
            startBtn.classList.remove('running');
            startBtn.innerHTML = '<span>Execute Universal Analysis</span> <i class="fa-solid fa-bolt"></i>';
        }
    });
});
